### ISSUE TITLE
Commande `add`

### ISSUE THREAD

**Issue by mbrehin** [mbrehin/git-training#3]
Structure du fichier : 
* [ ] un titre
* [ ] un description courte
* [ ] les options

Lien sur la page de listing des commandes

**Comment by OlivierRouland** [comment]
## Options

git add [--verbose | -v] [--dry-run | -n] [--force | -f] [--interactive | -i] [--patch | -p]
	  [--edit | -e] [--[no-]all | --[no-]ignore-removal | [--update | -u]]
	  [--intent-to-add | -N] [--refresh] [--ignore-errors] [--ignore-missing]
	  [--chmod=(+|-)x] [--] [<pathspec>…​]

**Comment by mbrehin** [comment]
@OlivierRouland est-ce que tu as terminé ?

**Comment by OlivierRouland** [comment]
@Javanatole à toi

**Comment by OlivierRouland** [comment]
OK
